# Generated by Django 5.1.6 on 2025-02-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_pacientes')),
                ('pagamento_em_dia', models.BooleanField(default=True)),
                ('queixa', models.CharField(choices=[('TDAH', 'Transtorno do Déficit de Atenção com Hiperatividade'), ('D', 'Depressão'), ('A', 'Ansiedade'), ('E', 'Estresse'), ('B', 'Bipolaridade'), ('S', 'Esquizofrenia'), ('O', 'Outro')], max_length=4)),
            ],
        ),
    ]
